### ISSUE TITLE
Build fails on systems with glibc 2.33

### ISSUE THREAD

**Issue by dedguy21** [ifreund/river#232] opened 2021-03-04 01:57 UTC
The wlroots version has been updated in the official Arch version to 12.0.1, getting a previous build error complaining about "libxkbcommon.so" that happened when it was wlroots master issue .

**Comment by ifreund** [comment] 2021-03-04 14:10
You're going to need to provide build logs for me to be able to be of any help. The latest wlroots release is 0.12.0, I don't know what version "12.0.1" would refer too. Please make sure that you are using zig version 0.7.1 and have all the submodules cloned and up to date.

**Comment by dedguy21** [comment] 2021-03-04 15:02
I apologize:

 sudo zig build -Drelease-safe -Dxwayland --prefix /usr install
```
warning: zig cannot build new glibc version 2.33; providing instead 2.32
ld.lld: error: /lib64/libxkbcommon.so: undefined reference to stat64@GLIBC_2.33 [--no-allow-shlib-undefined]
ld.lld: error: /lib64/libxkbcommon.so: undefined reference to fstat64@GLIBC_2.33 [--no-allow-shlib-undefined]
error: LLDReportedFailure
river...The following command exited with error code 1:
/usr/bin/zig build-exe /home/air/.cache/yay/river/river/main.zig --library c --library evdev --library wayland-server --library xkbcommon --library pixman-1 --library wlroots -cflags -std=c99 -- /home/air/.cache/yay/river/zig-cache/zig-wayland/xdg-shell-protocol.c -cflags -std=c99 -- /home/air/.cache/yay/river/zig-cache/zig-wayland/pointer-gestures-unstable-v1-protocol.c -cflags -std=c99 -- /home/air/.cache/yay/river/zig-cache/zig-wayland/xdg-output-unstable-v1-protocol.c -cflags -std=c99 -- /home/air/.cache/yay/river/zig-cache/zig-wayland/pointer-constraints-unstable-v1-protocol.c -cflags -std=c99 -- /home/air/.cache/yay/river/zig-cache/zig-wayland/river-control-unstable-v1-protocol.c -cflags -std=c99 -- /home/air/.cache/yay/river/zig-cache/zig-wayland/river-options-unstable-v1-protocol.c -cflags -std=c99 -- /home/air/.cache/yay/river/zig-cache/zig-wayland/river-status-unstable-v1-protocol.c -cflags -std=c99 -- /home/air/.cache/yay/river/zig-cache/zig-wayland/wlr-layer-shell-unstable-v1-protocol.c -cflags -std=c99 -- /home/air/.cache/yay/river/zig-cache/zig-wayland/wlr-output-power-management-unstable-v1-protocol.c --pkg-begin build_options /home/air/.cache/yay/river/zig-cache/river_build_options.zig --pkg-end -OReleaseSafe --cache-dir /home/air/.cache/yay/river/zig-cache --global-cache-dir /root/.cache/zig --name river --pkg-begin wayland /home/air/.cache/yay/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /home/air/.cache/yay/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /home/air/.cache/yay/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-begin wlroots /home/air/.cache/yay/river/deps/zig-wlroots/src/wlroots.zig --pkg-begin wayland /home/air/.cache/yay/river/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /home/air/.cache/yay/river/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /home/air/.cache/yay/river/deps/zig-pixman/pixman.zig --pkg-end --pkg-end -I /usr/include/libevdev-1.0 -I /usr/include/pixman-1 -I /usr/include/libdrm -I /usr/include/pixman-1 --enable-cache 
error: the following build command failed with exit code 1:
/home/air/.cache/yay/river/zig-cache/o/15710a01f4662a3188c4f38e4e771e5c/build /usr/bin/zig /home/air/.cache/yay/river /home/air/.cache/yay/river/zig-cache /root/.cache/zig -Drelease-safe -Dxwayland --prefix /usr install
```

**Comment by dedguy21** [comment] 2021-03-04 15:05
I will attempt another fresh install of Arch, just in case I somehow messed up wlroots libs by adding wdisplay-git and some other wlr related programs from AUR.

I really really love this tiling windows manager you have created.

**Comment by dedguy21** [comment] 2021-03-04 18:12
Also, I don't mind taking over the AUR maintenance, if you don't mind sharing the build packaging scripts for AUR. 

Thanks

**Comment by ifreund** [comment] 2021-03-04 18:18
Thanks for the logs, this seems to be an upstream issue with zig but I will try and find a workaround.

> Also, I don't mind taking over the AUR maintenance, if you don't mind sharing the build packaging scripts for AUR.

I use void these days and I think daurnimator is more than capable of maintaining the river-git AUR package. Thanks for the offer though.

**Comment by branwright1** [comment] 2021-03-08 13:01
Try downgrading glibc version, I'm having same issue but fixed it by installing river as prebuild binary-cache from my nix channel

**Comment by dedguy21** [comment] 2021-03-08 14:03
@branwright1 act like that screwed up my whole Arch system. Unfortunately I had just freshly reinstalled Arch so I didn't have any btrfs snapshots available to roll back to.

I'm liking the idea of using Nix more and more

**Comment by branwright1** [comment] 2021-03-08 19:49
So, I tried to compile river on downgraded glibc to 3.32 from 3.33 (nixos, void linux and arch linux) and still doesn't work for some reason (https://pastebin.com/4hWaKyAA) but on musl works fine (tested on: void linux musl, kiss linux and custom nixos install with musl)

**Comment by ifreund** [comment] 2021-03-09 11:44
The problem is that all of the library dependencies of river must be compiled against the same glibc version as river. This is a non-issue with musl as it doesn't use symbol versioning.

I haven't tried it yet, but it's probably possible to get zig to link against your system glibc 2.33 instead of providing its own glibc 2.32 by using the `--libc` flag of `zig build-exe`. This can also be set for `LibExeObjStep`s in the `build.zig` with `setLibcFile()`

**Comment by Leon-Plickat** [comment] 2021-03-09 15:44
Documenting the workaround:

```
zig libc > libc-paths
```

And then in `build.zig` add `.setLibCFile("libc-paths")` after every `.linkLibC()`.

**Comment by dedguy21** [comment] 2021-03-09 18:42
To verify that for arch  .setLibCFile('libc-paths")

is that litteral or would that be .setLibCFile("/usr/lib/pkgconfig/glib-2.0.pc")

**Comment by Leon-Plickat** [comment] 2021-03-09 19:04
On Tue Mar 9, 2021 at 7:42 PM CET, dedguy21 wrote:
>
> To verify that for arch .setLibCFile('libc-paths")
>
> is that litteral or would that be
> .setLibCFile("/usr/lib/pkgconfig/glib-2.0.pc")

It is literal. You are pointing it to the file created with the command

     zig libc >  libc-file

Friendly greetings,
Leon Henrik Plickat

**Comment by dedguy21** [comment] 2021-03-09 19:13
Ok, the build works... just to clarify for anyone else though

The work around is:
1) run the terminal command first:  zig libc > libc-paths
2) using your favorite text editor (nvim for me): find ".linkLibC()" instances ( i think there are three) and unerneath append the line for .setLibCFile("libc-paths") in file 'build-zig'
  example:
      found    -->              riverctl.linkLibC();
      insert next line -->  riverctl.setLibCFile("libc-paths")

Agian I believe there are three instances, save and then run the build per instructions

Thanks, this work around has resolved the build failure in Arch, and I have successfully build and run River

**Comment by dedguy21** [comment] 2021-03-09 19:38
So is there a downside to having this workaround just be the default behavior to avoid any future build errors with the next glib update?

**Comment by ifreund** [comment] 2021-03-09 20:11
> So is there a downside to having this workaround just be the default behavior to avoid any future build errors with the next glib update?

I plan to make this the default behavior of zig when linking system libraries. Solving this upstream is better for everyone.

I'm going to keep this issue open while river is still affected though so that people can find it more easily.

**Comment by ahmadraniri1994** [comment] 2021-03-20 07:45
Thanks for the trick.

**Comment by antaxiom** [comment] 2021-04-17 14:43
Hello, I've been trying to build the `river-layout-unstable-v1` branch of river and I'm encountering this very same set of errors even with this work around. I was told it was fixed so the workaround shouldn't be needed, but I'm encountering this. 
```
ld.lld: error: /lib64/libxkbcommon.so: undefined reference to stat64@GLIBC_2.33 [--no-allow-shlib-undefined]
ld.lld: error: /lib64/libxkbcommon.so: undefined reference to fstat64@GLIBC_2.33 [--no-allow-shlib-undefined]
error: LLDReportedFailure
river...The following command exited with error code 1:
```
The end of this message is too long so I decided to clip it, if needed I can add it later.

I would like to not I'm building with Xwayland, but this does not seem to be a factor in the failure. My build command is such `sudo zig build -Drelease-safe -Dxwayland --prefix /usr install` 

If anyone were to be knowledgeable on this that would be of great help, I may be making a small error in my process.

**Comment by ifreund** [comment] 2021-04-17 15:28
> Hello, I've been trying to build the `river-layout-unstable-v1` branch of river and I'm encountering this very same set of errors even with this work around. I was told it was fixed so the workaround shouldn't be needed, but I'm encountering this.

This branch doesn't change anything related to this issues, the workaround is still necessary.

**Comment by antaxiom** [comment] 2021-04-17 15:32
I did the workaround and I'm getting to new build errors, but they seem unrelated to this, thank you for your help.

**Comment by codic12** [comment] 2021-04-28 23:54
Is it possible to build River with musl instead?

**Comment by ifreund** [comment] 2021-04-29 09:07
> Is it possible to build River with musl instead?
> If I do the standard -Dtarget I get an error about `'wlr/config.h'` not found but strangely I don't get it if I don't use musl (I have wlroots installed).

Building river on a musl based system worked fine last time I tried, if it doesn't work for you please open a separate issue.

**Comment by codic12** [comment] 2021-04-29 15:02
Will do, thanks.

**Comment by branwright1** [comment] 2021-05-09 14:40
What about commenting `linkLibC` to compile all binaries as static linked by default until zig 0.8 becomes stable? This will eliminate problems on new glibc versions and forcing users to patch `builld.zig` (already tested)

**Comment by ifreund** [comment] 2021-05-09 15:56
> What about commenting `linkLibC` to compile all binaries as static linked by default until zig 0.8 becomes stable? This will eliminate problems on new glibc versions and forcing users to patch `builld.zig` (already tested)

unfortunately mesa can't be statically linked :/

**Comment by ifreund** [comment] 2021-05-12 09:01
This is now fixed upstream: https://github.com/ziglang/zig/pull/8737

I'll keep this issue open until zig 0.8.0 is released and river is updated.

**Comment by ifreund** [comment] 2021-05-23 12:45
river now has a `next-zig` branch compatible with zig master, which fixes this issue <https://github.com/ifreund/river/tree/next-zig>

**Comment by ifreund** [comment] 2021-06-05 20:04
zig 0.8.0 has been released and river has been updated.

**Closed by ifreund** 2021-06-05 20:04 UTC
Labels: build

**Comment by voroskoi** [comment] 2023-10-19 15:43
Just a note for guix users on manual building:
1. start shell with `guix shell gcc`
2. `export CC=gcc`
3. `zig libc > libc.zig`
4. `zig build --libc libc.zig -Doptimize=ReleaseSafe`
