### ISSUE TITLE
wlr_output_commit sometimes start to fail a lot

### ISSUE THREAD

**Issue by maringuu** [ifreund/river#153] opened 2020-11-18 20:42 UTC
Tested on [current master](cbd4a2807bcfa74cc87c36d7ec20cdf92a7c77fc) the rendering "freezes".

My setup consists of two outputs. One 1080p laptop display and an external 4k output connected via displayport.

I did the following:
1. Open river
2. Spawn a bunch of terminals (foot)
3. Change the layout a couple of times to cause calls to `root.startTransaction`
4. Now changing the layout did not result in a visual change
5. Change focus to my other output and spawn a terminal. I didn't see any visual change here either
6. Change VT back and fourth
7. Now the rendering works as expected

I can kind of reliably reproduce this. The steps above lead to this most of the time.

Here are the logs: https://paste.sr.ht/~maringuu/bb42efa93eeed27b3d8d53258c907ee9f2771f87

Here are some other logs where the rendering also froze: 
https://paste.sr.ht/~maringuu/862ccc42f315baeeadffcd20fe667ad604027689

Edit:
I figured out a simpler way to reproduce. It works very reliable for me.
1. Open river
2. Open at least two terminals (foot)
3. Do `riverctl swap next` a bunch of times until it freezes

**Comment by Leon-Plickat** [comment] 2020-11-18 21:28
Seems to be the same things I mentioned in IRC some time ago, with the difference that I can not reliably recreate it.

**Comment by maringuu** [comment] 2020-11-19 10:05
> Seems to be the same things I mentioned in IRC some time ago, with the difference that I can not reliably recreate it.

Interesting. It might have to do with bad/unusual hardware (at least for my external screen). My usb-c to displayport adapter has some unusual behavior. Sometimes the modes from the output are not detected. Also sometimes I cant enable the output.

Also I could reproduce this without starting any application at all. The error appeared instantly when starting river.

**Comment by travankor** [comment] 2020-12-03 01:19
I can reproduce this, too, so I doubt this is hardware related.

**Comment by maringuu** [comment] 2020-12-07 10:32
Another note that might be helpful: Today only one of my two outputs froze. Sadly I lost the logs somewhere.

**Comment by maringuu** [comment] 2020-12-08 10:18
Some more logs for future reference: https://paste.sr.ht/~maringuu/cd8118873f9970d95c8cb3fc6258bd5f96651a4b

**Comment by edrex** [comment] 2021-01-10 21:13
Seems like adding some debug code might be needed. I see this ~hourly

**Comment by edrex** [comment] 2021-01-11 07:24
What graphics hw are others experiencing this using? I have an XPS13 9360 QHD
 - `lspci -> Intel Corporation HD Graphics 620 (rev 02)`.
 - 4k laptop display with scale 2x
 - 1080p external monitor connected via thunderbolt HDMI adapter.

@maringuu @travankor @Leon-Plickat

**Comment by Leon-Plickat** [comment] 2021-01-11 07:28
```sh
$ lspci | grep Graph
00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
```

1920x1080 laptop display, plus either a 2560x1080 or a 1080x1920 monitor via plain HDMI.

**Comment by travankor** [comment] 2021-01-11 09:01
- `lspci` -> `00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)`
- 1920x1080 laptop display
- no external monitors

I will try this out on a ~2009 era nouveau machine later.

**Comment by maringuu** [comment] 2021-01-13 09:40
```sh
$ lspci | rg VGA
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
```

```sh
$ wlr-randr 
Head appeared
Head appeared
eDP-1 "Sharp Corporation 0x1484 0x00000000 (eDP-1)"
  Physical size: 290x170 mm
  Enabled: no
  Modes:
    1920x1080 px, 59.999001 Hz (preferred)
    1920x1080 px, 47.997002 Hz
DP-1 "Goldstar Company Ltd LG Ultra HD 0x0000F3B7 (DP-1)"
  Physical size: 600x340 mm
  Enabled: yes
  Modes:
    3840x2160 px, 59.997002 Hz (preferred, current)
    3840x2160 px, 30.000000 Hz
    2560x1440 px, 59.951000 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 59.939999 Hz
    1600x900 px, 60.000000 Hz
    1280x1024 px, 60.020000 Hz
    1280x800 px, 59.810001 Hz
    1152x864 px, 59.972000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 59.939999 Hz
    1024x768 px, 60.004002 Hz
    800x600 px, 60.317001 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 59.939999 Hz
    640x480 px, 60.000000 Hz
    640x480 px, 59.939999 Hz
    640x480 px, 59.939999 Hz
  Position: 0,0
  Transform: normal
  Scale: 1.500000
```

**Comment by edrex** [comment] 2021-01-13 09:56
@travankor interesting that you see this with only one output. I only see it with an external display connected (although it randomly affects either output)

**Comment by edrex** [comment] 2021-01-14 03:52
One detail from my experience sticks out: The output that freezes is always the one I'm not using. It happens very frequently, but never on the focused output. 

It seems like something is going stale by not being exercised. I wonder if the time from last interaction with that output till freeze is consistent. I'm running waybar with a clock, so I'm going to do some trials to find out.

**Comment by edrex** [comment] 2021-01-15 07:54
Possibly related (same ERRNO) although it happens on hotplug instead of just whenever:
[Atomic commit sometimes fails with EBUSY on hotplug (#24) · Issues · wayland / weston · GitLab](https://gitlab.freedesktop.org/wayland/weston/-/issues/24)

**Comment by novakne** [comment] 2021-02-19 14:03
Is there some news about this? 
I also have this issue frequently, it happen on river and dwl but not on sway
I only have one screen, a laptop 1920x1080, no other monitors 
```
$ lspci | rg Graph  
00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
```
Nothing in `journalctl -p 3..1 -xb`

River log:
```
00:00:37.309 [ERROR] [backend/drm/atomic.c:36] eDP-1: Atomic commit failed (pageflip): Device or resource busy
err: (render) output commit failed for eDP-1
```

**Comment by ifreund** [comment] 2021-03-27 15:18
Fixed in c457b12cf3c2040f37f9322095a20ad16a15b337

**Comment by ifreund** [comment] 2021-03-28 12:00
workaround reverted in 3c1f1df0c0faa561f5f993e05ba0c8ad3e56954f as it caused infinite loops when the output commit did not fail with EBUSY (e.g. when failing with EPERM on switching ttys).

**Comment by Q-I-U** [comment] 2021-03-30 06:52
How can I reproduce the bad behavior in c457b12cf3c2040f37f9322095a20ad16a15b337?

**Comment by novakne** [comment] 2021-03-30 13:31
@Q-I-U For me the infinite loop happened doing this:
1. Launch River in TTY1
2. Switch to TTY2 and switch back to TTY1

Then `[backend/drm/atomic.c:36] eDP-1: Atomic commit failed (pageflip): Permission denied`
And reposting what i show in river freenode, my screen is like this [Imgur](https://imgur.com/DvZAyTE)

**Comment by Q-I-U** [comment] 2021-03-30 14:31
Ok, I didn't notice this issue because I'm running River with seatd. Maybe I'll figure something out to fix this.

**Comment by novakne** [comment] 2021-04-02 10:03
Same issue in TinyWL and dwl too, same error in every wayland compositor with no damage tracking
`00:25:06.907 [ERROR] [backend/drm/atomic.c:36] eDP-1: Atomic commit failed (pageflip): Device or resource busy`

**Comment by Q-I-U** [comment] 2021-04-02 10:14
For me the same error happens also on sway. The difference is that on sway it doesn't make the compositor freeze.
Also it looks like the infinite loops from c457b12cf3c2040f37f9322095a20ad16a15b337 don't happen on FreeBSD at all, even when I tried running river without seatd. I guess I have to setup a linux vm to troubleshoot this further.

**Comment by novakne** [comment] 2021-04-02 10:19
So that almost confirm that it is a wlroots error but damage tracking hide it, or at least without freeze you don't pay attention to it

**Comment by Q-I-U** [comment] 2021-04-02 10:26
Yeah, I also thought that this might be the case when I was comparing Sway's rendering code with River's. But this isn't confirmed yet so I think for now we should still try to fix the problem without touching external libraries.

**Comment by novakne** [comment] 2021-04-02 11:05
Ok so I tried and I can confirm that I have the same error in sway too, there just no freeze so you don't see it if you don't look at the log.

**Comment by Q-I-U** [comment] 2021-04-03 10:04
I managed to reproduce the error when switching ttys on a Linux mint machine:
```
00:00:09.872 [ERROR] [backend/drm/atomic.c:36] VGA-1: Atomic commit failed (pageflip): Permission denied
```
But It didn't make the compositor freeze, so I still have to work out how to reproduce the issue.
In the meantime I made a small change in my [River fork](https://github.com/Q-I-U/river) that might solve this problem. I changed `renderOutput()` so that it always schedules a frame. It still prevents EBUSY freezes and I hope that It will also prevent the EPERM freezes.

Please let me know if this change makes any difference.

**Comment by novakne** [comment] 2021-04-03 10:37
> But It didn't make the compositor freeze, so I still have to work out how to reproduce the issue.

When it failed with permission denied it doesn't freeze,  your previous workaround c457b12 fix the freeze but created an infinity loop and messed up the screen

Let me test your fork

**Comment by novakne** [comment] 2021-04-03 11:28
<details>
  <summary>Well, still mess with my screen </summary>
  
  ![river_error](https://user-images.githubusercontent.com/11297405/113476959-17717100-947f-11eb-9ca3-94212103ee72.jpg)
  
</details>

Still have an infinite loop, I'm not gonna share the log since it has like 13 000 lines but it looks like it start with a loop of EPERM error and then a loop of EBUSY.
I think when I switch to TTY2 it start the infinite loop of EPERM but when I switch back to TTY1 it the start the infinite loop of EBUSY

**Comment by Q-I-U** [comment] 2021-04-03 11:36
Welp, it that case I'll have to try something else. If I find a different way of fixing this I'll post an update here.

**Comment by ifreund** [comment] 2021-04-03 12:28
If we were to only retry on EBUSY but not EPERM the workaround would likely work fine and avoid the issues with switching ttys. However this would require modifications to wlroots and I doubt such a workaround would be accepted upstream.

As for where the actual bug is, I'm fairly confident that wlroots's drm backend is at fault as the EBUSY has been observed on tinywl, dwl, and sway in addition to river. The difference is that there is no observed freeze on sway as the damage tracking code causes another frame to be scheduled regardless of output commit failure. Therefore, I would expect a proper fix for this bug to be in the wlroots drm backend.

**Comment by novakne** [comment] 2021-04-03 12:58
Yeah I can't see how we could fix this without touching to wlroots, either we need to implement damage tracking and we just hide the problem or it need to be fix on wlroots end

I tried to get a DRM log but since te problem is random I get like 250 000 lines of log and I have no idea what to look for since there no mentions of errors, warn or  whatever

**Comment by Q-I-U** [comment] 2021-04-04 19:17
I changed the fix on my [fork](https://github.com/Q-I-U/river) to use damage tracking.
(I didn't implement proper damage tracking, just enough to prevent the freezes)
Can someone test if the EPERM problem is still present?
(Sorry, but I'm not able to reproduce it on any of my *nix machines)

**Comment by novakne** [comment] 2021-04-04 20:13
Still have it
Would be ' great' if someone else could reproduce the EPERM too, to be sure it's not something in my end, even if I cant see why it would be the case

**Comment by novakne** [comment] 2021-04-05 08:18
@Q-I-U feel free to ask me if you need specific test or anything to help

**Comment by Leon-Plickat** [comment] 2021-05-23 13:52
See also https://github.com/swaywm/wlroots/issues/2937

**Closed** 2021-05-24 14:43 UTC
Labels: bug
