### ISSUE TITLE
River randomly becomes unresponsive

### ISSUE THREAD

**Issue by ReneganRonin** [ifreund/river#295] opened 2021-05-22 08:20 UTC
**OS**
Arch Linux

**Kernel**
5.12.5-arch1-1

**CPU**
Intel Pentium N3530 (4) @ 2.582GHz

**GPU**
Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display

**Problem**
I installed river from the AUR specifically `river-git`. It installed successfully. However, running it was fine at first but at random times, it suddenly becomes unresponsive. I just switch to another tty and then go back to the tty that ran river and river becomes responsive again. After a few random times or so, the behavior happens again so I do that back and forth tty thing.

**Expected Behavior**
It should not become unresponsive all of a sudden.

**Comment by novakne** [comment] 2021-05-22 09:11
It is a known bug on wlroots based compositor without damage tracking, see #153

**Comment by ifreund** [comment] 2021-05-22 09:12
Closing as duplicate of #153

**Closed by ifreund** 2021-05-22 09:12 UTC
