### ISSUE TITLE
Doesn't build on aarch64

### ISSUE THREAD

**Issue by malte-v** [ifreund/river#105] opened 2020-09-28 09:27 UTC
Hi! I'm trying to build this on NixOS. I've added `libevdev` to the shell.nix in the Wiki since it was apparently missing, but now I'm getting this error:

```
[nix-shell:~/river]$ zig build -Drelease-safe=true --prefix ./out install
Semantic Analysis [604/865] ./zig-cache/o/_ZROy3lqpPYwM0LfP0uL18zTXufkaKMtOhlQ3QwciuigoSLQKwVO7KO_vPoCin0U/cimport.zig:1288:21: error: use of undeclared identifier '__builtin_va_list'
pub const va_list = __builtin_va_list;
                    ^
./zig-cache/o/_ZROy3lqpPYwM0LfP0uL18zTXufkaKMtOhlQ3QwciuigoSLQKwVO7KO_vPoCin0U/cimport.zig:6511:72: note: referenced here
pub const wlr_log_func_t = ?fn (enum_wlr_log_importance, [*c]const u8, va_list) callconv(.C) void;
                                                                       ^
./zig-cache/o/_ZROy3lqpPYwM0LfP0uL18zTXufkaKMtOhlQ3QwciuigoSLQKwVO7KO_vPoCin0U/cimport.zig:6512:74: note: referenced here
pub extern fn wlr_log_init(verbosity: enum_wlr_log_importance, callback: wlr_log_func_t) void;
                                                                         ^
./river/main.zig:68:6: note: referenced here
    c.wlr_log_init(.WLR_ERROR, null);
     ^
river...The following command exited with error code 1:
/nix/store/mgsj3c99v76q1xypjy2dxg7p97cvcz62-zig-0.6.0/bin/zig build-exe /home/malte/river/river/main.zig --c-source -std=c99 /home/malte/river/protocol/river-control-unstable-v1-protocol.c --c-source -std=c99 /home/malte/river/protocol/river-status-unstable-v1-protocol.c --c-source -std=c99 /home/malte/river/include/bindings.c --library c --library evdev --library pixman-1 --library wayland-server --library wlroots --library xkbcommon --pkg-begin build_options /home/malte/river/zig-cache/river_build_options.zig --pkg-end --release-safe --cache-dir /home/malte/river/zig-cache --name river -I /home/malte/river/protocol -I /home/malte/river -I /nix/store/rwd7kxy9jmn8c6w47ynmysrjay122rbv-libevdev-1.9.1/include/libevdev-1.0 -I /nix/store/xa6x1k3l1il4jqwqp54s6k20fmshfbw8-pixman-0.38.4/include/pixman-1 -I /nix/store/xx0hqxvpvxr9xvp2ybyv5p20jd4hn4zn-wayland-1.18.0/include -I /nix/store/w1l37yr22x7p099fahw50wyna8f9cl59-wlroots-0.11.0/include -I /nix/store/q1iarvdn7r04jg1lvvcp2kfjd2244nlr-libxkbcommon-0.10.0-dev/include -L /nix/store/rwd7kxy9jmn8c6w47ynmysrjay122rbv-libevdev-1.9.1/lib -L /nix/store/xa6x1k3l1il4jqwqp54s6k20fmshfbw8-pixman-0.38.4/lib -L /nix/store/xx0hqxvpvxr9xvp2ybyv5p20jd4hn4zn-wayland-1.18.0/lib -L /nix/store/w1l37yr22x7p099fahw50wyna8f9cl59-wlroots-0.11.0/lib -L /nix/store/fgxq3nrj5gf6ga0mbdjw0lbbwmhb3xal-libxkbcommon-0.10.0/lib --cache on 

Build failed. The following command failed:
/home/malte/river/zig-cache/o/3-L2BaKBzJ0hlgoBeTPbpF-ApupmSgcONLWrrqEJRP77tPSen9Ak6VRAPq_22sMn/build /nix/store/mgsj3c99v76q1xypjy2dxg7p97cvcz62-zig-0.6.0/bin/zig /home/malte/river /home/malte/river/zig-cache -Drelease-safe=true --prefix ./out install
```

Any idea what could have gone wrong here? Thanks!

**Comment by ifreund** [comment] 2020-09-28 14:21
Hmm, I haven't seen this error before, another good reason to create manual wlroots bindings. What  libc version are you using? Perhaps that's the cause, I'm not sure what else could be.

**Comment by malte-v** [comment] 2020-10-02 14:38
I forgot to mention that I'm on aarch64, sorry!

**Comment by FoundOne** [comment] 2020-10-02 15:02
I have the same issue on Manjaro-arm unstable.

**Comment by FoundOne** [comment] 2020-10-09 05:51
That looks like a bug in zig for aarch64, because __builtin_va_list should be taken form gcc or llvm (by that what I see in stdarg.h), but neither of the #ifdef blocks gets executed. I'm not a C expert tho.

**Comment by ifreund** [comment] 2020-10-09 13:38
Yes this is almost certainly a bug/missing feature of zig's translate-c. If you have the time, some investigation and a clear bug report for the zig repo would be helpful.

**Comment by ifreund** [comment] 2020-11-29 20:41
I was able to produce `river.o` cross-compiling to aarch64 with #159 (although the build failed due to some other issue introduced by cross compiling). I don't have an aarch64 machine to test on but I think  #159 should close this issue.

**Closed** 2020-12-13 21:53 UTC
Labels: bug, build
