### ISSUE TITLE
Natural Scrolling

### ISSUE THREAD

**Issue by ElPresidentePoole** [ifreund/river#250] opened 2021-03-30 05:28 UTC
Hello, it appears that there is no way to enable natural scrolling in river.  I'm coming from dwm with natural scrolling enabled in Xorg.conf.  Unless I am mistaken, there doesn't seem to be anything in riverctl to change the scroll behavior.

**Comment by ifreund** [comment] 2021-03-30 15:24
Closing as a duplicate of  #71. You may be interested in [libinput-config](https://gitlab.com/kirbykevinson/libinput-config) as a workaround until this is implemented.

**Closed by ifreund** 2021-03-30 15:24 UTC
