### ISSUE TITLE
Laggy cursor on native wayland programs.

### ISSUE THREAD

**Issue by Scupake** [ifreund/river#161] opened 2020-11-29 13:13 UTC
For some reason the cursor becomes very laggy when it's passing above a wayland program, Xwayland programs don't have that issue, I only used wayland twice and I didn't have this problem the first time (On Gnome shell). I also had weird cursor behavior on a game called Teeworlds.

**Comment by ifreund** [comment] 2020-11-29 16:21
I'm unable to reproduce this, could you give more details? What graphics card/driver do you have?

**Comment by Scupake** [comment] 2020-11-29 17:20
iGPU: Intel 82Q35 Express
Driver: i915

**Comment by Scupake** [comment] 2020-11-29 17:22
I'll go try sway, to see if it's an issue with wlroots or just river.

**Comment by Scupake** [comment] 2020-11-29 17:44
Seems like it's an issue with river, there are random slowdowns on sway (doesn't happen on river) but the cursor doesn't lag, so it could also just be wayland being weird.

**Comment by travankor** [comment] 2020-12-03 01:27
Could be the same as #153 although your description is a little vague (the cursor freezes for me but so does the rest of the screen, for instance).

**Comment by Scupake** [comment] 2020-12-03 18:05
It doesn't freeze for me, it's just very sluggish and laggy, everything else is completely normal

**Comment by ifreund** [comment] 2020-12-06 18:31
Any chance that wlroots is falling back to software rendering on your system? It would likely be noticeably worse on river than sway as we do not have damage tracking implemented yet.

**Comment by Scupake** [comment] 2020-12-06 19:33
It could be possible, my iGPU is very old and had lots of openGL issues, most of them got fixed though.

**Comment by snakedye** [comment] 2020-12-22 20:47
@ifreund I think I'm experiencing the same issue, here's a clip

cpu: AMD Ryzen 5 2600
gpu: AMD RX570

https://gofile.io/d/etUO3f

**Comment by ifreund** [comment] 2020-12-27 14:41
> @ifreund I think I'm experiencing the same issue, here's a clip
> 
> cpu: AMD Ryzen 5 2600
> gpu: AMD RX570
> 
> https://gofile.io/d/etUO3f

What I see in that video is #109

**Comment by ifreund** [comment] 2020-12-27 15:14
@snakedye well I've fixed the issue I saw in that video in 055fba5c3c9f4a6c8cd248507cfee299deca32e0. I'm no longer sure if #109 was related or not, will check that out next.

Can anyone reproduce this after 055fba5c3c9f4a6c8cd248507cfee299deca32e0?

**Comment by FollieHiyuki** [comment] 2021-01-03 16:32
https://user-images.githubusercontent.com/67634026/103483588-5862d680-4df9-11eb-87e6-97c04c493687.mp4

I have this problem that might seem related. In the video I dragged the cursor vertically but it didn't behave right.

This occurs on both Wayland and Xwayland apps but only on 1 output (I have 2 monitors setup and the cursor acts normally on the other one).

**Comment by ifreund** [comment] 2021-01-07 10:30
@FollieHiyuki the problem I see there is #186 and was fixed in b468f0aa8502e0cec985f4a9f799c292565f5dcf

I'm going to go ahead and close this issue as it's become a bit of a grab bag of cursor-related problems. If anybody can still reproduce a bug please open a new issue for it.

**Closed by ifreund** 2021-01-07 10:30 UTC
