### ISSUE TITLE
Error while building on glibc 2.32.0 system

### ISSUE THREAD

**Issue by loFiWaterCat** [ifreund/river#95] opened 2020-09-07 23:17 UTC
Hi, relatively new to linux, so not really knowledgeable about what's going on. I was interested in your wm so I wanted to try it out, but I ran into this error while building the package on arch.

Build failed. The following command failed:
/home/lofiwatercat/builds/river-git/src/river/zig-cahce/o/7CMTxuEiAs3DkNZRezZBueLAuybfeMYo9htEkoLHBzaOqWHPdmPed60bWPC58enh/build /usr/bin/zig /home/lofiwatercat/builds/river-git/src/river /home/lofiwatercat/builds/river-git/src/river/zig-cache -Drelease-safe

The error occurred when I ran makepkg -si after cloning the repo.

**Comment by ifreund** [comment] 2020-09-08 13:41
Hello, it looks like you've only pasted the last part of the error message, could you paste the full error?

At a guess though this is likely caused by arch having recently upgraded glibc and zig 0.6.0 being incompatible with this newer version. The easiest fix for this would be to do grab a recent master build of zig from <https://ziglang.org/download/> and use the `next-zig` branch.

**Comment by loFiWaterCat** [comment] 2020-09-09 02:53
Sorry about that, here's the entire error:
    river ... Skipped
Reset branch 'makepkg'
Unrecognized glibc version: 2.32.0
unrecognized C ABI
river...The following command exited with error code 1:
/usr/bin/zig build-exe /home/lofiwatercat/builds/river-git/src/river/river/main.zig --c-source -std=c99 /home/lofiwatercat/builds/river-git/src/river/protocol/river-control-unstable-v1-protocol.c --c-source -std=c99 /home/lofiwatercat/builds/river-git/src/river/protocol/river-status-unstable-v1-protocol.c --c-source -std=c99 /home/lofiwatercat/builds/river-git/src/river/include/bindings.c --library c --library evdev --library pixman-1 --library wayland-server --library wlroots --library xkbcommon --pkg-begin build_options /home/lofiwatercat/builds/river-git/src/river/zig-cache/river_build_options.zig --pkg-end --release-safe --cache-dir /home/lofiwatercat/builds/river-git/src/river/zig-cache --name river -I /home/lofiwatercat/builds/river-git/src/river/protocol -I /home/lofiwatercat/builds/river-git/src/river -I /usr/include/libevdev-1.0 -I /usr/include/pixman-1 -I /usr/include/libdrm -I /usr/include/pixman-1 --cache on 

Build failed. The following command failed:
/home/lofiwatercat/builds/river-git/src/river/zig-cache/o/7CMTxuEiAs3DkNZRezZBueLAuybfeMYo9htEkoLHBzaOqWHPdmPed60bWPC5Senh/build /usr/bin/zig /home/lofiwatercat/builds/river-git/src/river /home/lofiwatercat/builds/river-git/src/river/zig-cache -Drelease-safe
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by ifreund** [comment] 2020-09-09 08:55
This does indeed look to be caused by having a newer system glibc version than zig 0.6.0 supports installed. I haven't found a way to build river with zig 0.6.0 on such a system yet, for now the solution is to use a recent master build of zig plus the [next-zig](https://github.com/ifreund/river/tree/next-zig) branch.

For reference, the zig issue on this problem is here: https://github.com/ziglang/zig/issues/4487

**Comment by tsujp** [comment] 2020-09-09 15:48
For extra log information here is a log with `glibc 2.32-2` from Arch

```
(i) ~ > yay -S river-git
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  river-git-r264.59d0fb7-1

  1 river-git                                (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): river-git
  1 river-git                                (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: river-git
==> Making package: river-git r264.59d0fb7-1 (Wed 09 Sep 2020 23:45:15 AWST)
==> Retrieving sources...
  -> Updating river git repo...
Fetching origin
==> Validating source files with md5sums...
    river ... Skipped
==> Making package: river-git r264.59d0fb7-1 (Wed 09 Sep 2020 23:45:17 AWST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating river git repo...
Fetching origin
==> Validating source files with md5sums...
    river ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of river git repo...
Cloning into 'river'...
done.
==> Starting pkgver()...
==> Updated version: river-git r425.976a3ce-1
==> Sources are ready.
==> Making package: river-git r425.976a3ce-1 (Wed 09 Sep 2020 23:45:20 AWST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Build Dependencies...Unrecognized glibc version: 2.32.0
unrecognized C ABI
river...The following command exited with error code 1:
/usr/bin/zig build-exe /home/tsujp/.cache/yay/river-git/src/river/river/main.zig --c-source -std=c99 /home/tsujp/.cache/yay/river-git/src/river/protocol/river-control-unstable-v1-protocol.c --c-source -std=c99 /home/tsujp/.cache/yay/river-git/src/river/protocol/river-status-unstable-v1-protocol.c --c-source -std=c99 /home/tsujp/.cache/yay/river-git/src/river/include/bindings.c --library c --library evdev --library pixman-1 --library wayland-server --library wlroots --library xkbcommon --pkg-begin build_options /home/tsujp/.cache/yay/river-git/src/river/zig-cache/river_build_options.zig --pkg-end --release-safe --cache-dir /home/tsujp/.cache/yay/river-git/src/river/zig-cache --name river -I /home/tsujp/.cache/yay/river-git/src/river/protocol -I /home/tsujp/.cache/yay/river-git/src/river -I /usr/include/libevdev-1.0 -I /usr/include/pixman-1 -I /usr/include/libdrm -I /usr/include/pixman-1 --cache on 

Build failed. The following command failed:
/home/tsujp/.cache/yay/river-git/src/river/zig-cache/o/Ys5ZWNkelLKJJ_3NwRicPdT2Zq0YaVuQu20ONp43bAXrBw88Jinn2GdFJXVt2YMm/build /usr/bin/zig /home/tsujp/.cache/yay/river-git/src/river /home/tsujp/.cache/yay/river-git/src/river/zig-cache -Drelease-safe
==> ERROR: A failure occurred in build().
    Aborting...
error making: river-git
```

**Comment by andrewrk** [comment] 2020-09-09 17:16
Thanks for this info. Apologies for this, it was an oversight in the original implementation of this feature for Zig. Will be sure that issue gets solved in the upcoming Zig 0.7.0 release at the end of this month. I'll be sure to test the code path for when the system glibc is newer than the available glibc zig can provide, so that we don't have a repeat of this incident with glibc 2.33.

**Comment by tsujp** [comment] 2020-09-09 17:23
Thank you for your hard work @andrewrk and @ifreund

**Comment by Houkime** [comment] 2020-09-26 11:13
> This does indeed look to be caused by having a newer system glibc version than zig 0.6.0 supports installed. I haven't found a way to build river with zig 0.6.0 on such a system yet, for now the solution is to use a recent master build of zig plus the [next-zig](https://github.com/ifreund/river/tree/next-zig) branch.
> 
> For reference, the zig issue on this problem is here: [ziglang/zig#4487](https://github.com/ziglang/zig/issues/4487)

unfortunately, zig-master 0.6.0+a50260470  https://github.com/ziglang/zig/commit/a502604702726f3983f8a8b80bb73d9d5381baab currently fails to build river with 

```
./build.zig:142:41: error: expected type 'std.build.Id', found '*const [14:0]u8'
            .step = std.build.Step.init("Scan Protocols", builder.allocator, make),
                                        ^
/usr/lib/zig/std/build.zig:2556:20: note: std.build.Id declared here
    pub const Id = enum {
                   ^
./build.zig:237:41: error: expected type 'std.build.Id', found '*const [18:0]u8'
            .step = std.build.Step.init("Generate man pages", builder.allocator, make),
                                        ^
/usr/lib/zig/std/build.zig:2556:20: note: std.build.Id declared here
    pub const Id = enum {
                   ^

```
seems like API change.

So using zig-master as a workaround is not really an option.

**Comment by ifreund** [comment] 2020-09-26 11:22
@Houkime the `next-zig` branch is here, and handles that API change among others: https://github.com/ifreund/river/tree/next-zig

**Comment by Houkime** [comment] 2020-09-28 03:47
> @Houkime the `next-zig` branch is here, and handles that API change among others: https://github.com/ifreund/river/tree/next-zig
> 
> If you're still having trouble, feel free to stop by `#river` on `irc.freenode.net`.

ah, ok, it is a branch of river then. Misunderstood that at first. sorry. thx
builds now

**Comment by andrewrk** [comment] 2020-09-30 09:01
This is solved in master branch so it won't happen again, with the release of glibc 2.33, however I am leaving the issue open until I have simulated the situation happening to make sure it truly does work.

**Comment by tsujp** [comment] 2020-09-30 09:03
This builds for me using the `next-zig` branch here and using the master branch of zig @andrewrk , tested via the HEAD of `next-zig` and [this commit](https://github.com/ziglang/zig/commit/bd449b184a0c9fb824184672b12f90ed2698b77a) (from today) of Zig.

**Comment by andrewrk** [comment] 2020-09-30 09:04
> however I am leaving the issue open

oops I thought I was on the zig issue tracker, sorry!

**Comment by tsujp** [comment] 2020-09-30 09:04
We're all Zig now.

**Comment by ifreund** [comment] 2020-10-05 21:18
I've updated the master branch to depend on zig master, so this should no longer be an issue with river.

**Closed by ifreund** 2020-10-05 21:18 UTC
Labels: bug, build
