### ISSUE TITLE
Dialog box does not reappear in QT XWayland application

### ISSUE THREAD

**Issue by ecocode** [ifreund/river#437] opened 2021-09-24 11:03 UTC
Using ARES Commander (an autocad clone with native linux port) as a QT Xwayland application I launch the Print dialog, which correctly appears and hides correctly to let me select a region to be printed.  However the dialog should reappear after the selection is made, but it does not.  The dialofg seems to be active still, but hidden.  I need to press escape to get back to the main application window.
Check the linked videos to see a failing river vs a correctly working sway.

https://imgur.com/a/Ya7xeVD

**Comment by ifreund** [comment] 2021-09-24 11:04
I wonder if this has the same root cause as  #436

**Comment by ecocode** [comment] 2021-09-24 11:28
Maybe it will help that I get this message when the dialog gets created (and shows up).  Nothing special in the logs after that..

```QObject::connect: No such slot CFxDlgPrintUI_Default::reloadSheetConfig()```

**Comment by ifreund** [comment] 2021-10-02 12:50
Should be fixed by 9270a2df08b8fad97203baedf133ac0b4fc47048

**Closed by ifreund** 2021-10-02 12:50 UTC
Labels: bug, xwayland

**Comment by ecocode** [comment] 2021-10-02 16:16
> Should be fixed by [9270a2d](https://github.com/ifreund/river/commit/9270a2df08b8fad97203baedf133ac0b4fc47048)

I confirm this bug is fixed

**Comment by ifreund** [comment] 2021-10-02 16:17
Excellent, thanks for confirming. I didn't test this with ARES Commander specifically.
